services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: edusmart-postgres
    environment:
      POSTGRES_DB: edusmart_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "101145"
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - edusmart-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: edusmart-redis
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    networks:
      - edusmart-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3
    command: redis-server --appendonly yes

  # MySQL Alternative (Comment out PostgreSQL and use this if preferred)
  # mysql:
  #   image: mysql:8.0
  #   container_name: edusmart-mysql
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: edusmart_db
  #     MYSQL_USER: edusmart
  #     MYSQL_PASSWORD: edusmart123
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - mysql_data:/var/lib/mysql
  #   networks:
  #     - edusmart-network
  #   restart: unless-stopped

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  # mysql_data:
  #   driver: local

networks:
  edusmart-network:
    driver: bridge
